### ISSUE TITLE
Error while installing davidban77.gns3

### ISSUE THREAD

**Issue by nabilovski** [davidban77/ansible-collection-gns3#15]
This happened to me while trying use the first example:
what I did:
pip install gns3fy mazer
     this was installed normally 

but this one didn't:
 mazer install davidban77.gns3
        Error loading configuration file /root/.ansible/mazer.yml:
       mapping values are not allowed here
        in "/root/.ansible/mazer.yml", line 4, column 16
Thanks.

**Comment by davidban77** [comment]
It looks like you have an issue on your `/root/.ansible/mazer.yml` file configuration. 

Can you take a look at your mazer file?. Here is an example one from Ansible doc:

```
version: 1
server:
  ignore_certs: false
  url: https://galaxy-qa.ansible.com
  api_key: da39a3ee5e6b4b0d3255bfef95601890afd80709
collections_path: ~/.ansible/collections
global_collections_path: /usr/share/ansible/collections
```

The error says `mapping values are not allowed here`, so my guess is that some variable is not set correctly
